services:
  - type: web
    name: military-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: ADMIN_PASSWORD
        sync: false
      - key: COMMANDER_PASSWORD
        sync: false
      - key: LOGISTICS_PASSWORD
        sync: false
